### ISSUE TITLE
pub get fails with 4.2.0 depends on analyzer >=1.0.0 <3.0.0

### ISSUE THREAD

**Issue by pxsanghyo** [marcglasberg/i18n_extension#108]
for current version
```yaml
name: i18n_extension
version: 4.2.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
```

so why am I getting this version solving failed message?

```
Because no versions of freezed match >1.1.1 <2.0.0 and freezed 1.1.1 depends on analyzer ^3.0.0, freezed ^1.1.1 requires analyzer ^3.0.0.

And because flutter_quill >=3.9.6 depends on i18n_extension ^4.2.0 which depends on analyzer >=1.0.0 <3.0.0, freezed ^1.1.1 is incompatible with flutter_quill >=3.9.6.
```

why does it say `i18n_extension ^4.2.0 which depends on analyzer >=1.0.0 <3.0.0`?
